version: '3.8'

services:
  mongo1:
    image: mongo:7.0.15
    container_name: mongo1
    ports:
      - "27017:27017"
    command: mongod --dbpath /data/db --replSet mgs --wiredTigerCacheSizeGB 1 --oplogSize 1000

  mongo2:
    image: mongo:7.0.15
    container_name: mongo2
    ports:
      - "27018:27017"
    command: mongod --dbpath /data/db --replSet mgs --wiredTigerCacheSizeGB 1 --oplogSize 1000

  mongo3:
    image: mongo:7.0.15
    container_name: mongo3
    ports:
      - "27019:27017"
    command: mongod --dbpath /data/db --replSet mgs --wiredTigerCacheSizeGB 1 --oplogSize 1000
