services:
  # mqnamesrv:
  #   image: apache/rocketmq:5.3.1
  #   container_name: mqnamesrv
  #   command: sh mqnamesrv -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
  #   ports:
  #     - "9876:9876" 
  #   restart: unless-stopped
  #   volumes:
  #     - ./namesvr.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf

  mqbroker:
    image: apache/rocketmq:5.3.1
    container_name: mqbroker
    command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    # depends_on:
      # - mqnamesrv
    ports:
      - "10911:10911"
      - "10909:10909"
    volumes:
      - ./runbroker.sh:/home/rocketmq/rocketmq-5.3.1/bin/runbroker.sh
      - ./broker.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf
    restart: unless-stopped

  # mqbroker_a_1:
  #   image: apache/rocketmq:5.3.1
  #   container_name: mqbroker_a_1
  #   command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
  #   # depends_on:
  #     # - mqnamesrv
  #   ports:
  #     - "30911:10911"
  #     - "30909:10909"
  #   volumes:
  #     - ./runbroker.sh:/home/rocketmq/rocketmq-5.3.1/bin/runbroker.sh
  #     - ./a_1.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf
  #   restart: unless-stopped

  # mqbroker_a_2:
  #   image: apache/rocketmq:5.3.1
  #   container_name: mqbroker_a_2
  #   command: sh mqbroker -c /home/rocketmq/rocketmq-5.3.1/conf/broker.conf
  #   # depends_on:
  #     # - mqnamesrv
  #   ports:
  #     - "30921:10911"
  #     - "30919:10909"
  #   volumes:
  #     - ./runbroker.sh:/home/rocketmq/rocketmq-5.3.1/bin/runbroker.sh
  #     - ./a_2.conf:/home/rocketmq/rocketmq-5.3.1/conf/broker.conf
  #   restart: unless-stopped

  mqdashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: mqdashboard
    environment:
      # JAVA_OPTS: "-Drocketmq.namesrv.addr=172.28.41.59:9876"
      JAVA_OPTS: "-Drocketmq.namesrv.addr=172.28.32.1:9876"
    ports:
      - "8080:8080"
    restart: unless-stopped
    # depends_on:
      # - mqnamesrv
