services:
  mqnamesrv:
    image: apache/rocketmq:5.3.1
    container_name: mqnamesrv
    command: sh mqnamesrv
    ports:
      - "9876:9876" 
    restart: unless-stopped

  mqbroker:
    image: apache/rocketmq:5.3.1
    container_name: mqbroker
    command: sh mqbroker -n mqnamesrv:9876
    depends_on:
      - mqnamesrv
    ports:
      - "10911:10911"
      - "10909:10909"
    volumes:
      - ./runbroker.sh:/home/rocketmq/rocketmq-5.1.4/bin/runbroker.sh
    restart: unless-stopped

  mqdashboard:
    image: apacherocketmq/rocketmq-dashboard:1.0.0
    container_name: mqdashboard
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=mqnamesrv:9876"
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - mqnamesrv
      - mqbroker
